/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons({"color": "pink"});
  // on Android, a nasty hack is needed: {"resizeClear": true}

  // you can add a canvas by it's ID...
  //today
  //skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);



  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start animation!
  skycons.play();
  
  // want to change the icon? no problem:
  //skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
  
/*
Get value from Bootstrap dropdown menu
*/
$('#dropdown li').on('click', function(){
    alert($(this).text());
});


//Today's weather
$(document).ready(function() {
  $.simpleWeather({
    woeid: '2306179', //taipei
    location: '',
    unit: 'c',
    success: function(weather) {
      html = '<h2>'+weather.temp+'&deg;'+weather.units.temp+'</h2>';
      html += '<p>'+weather.forecast[1].date+'<p>'
      html += '<p class="currently">'+weather.currently+'</p>';
      html += '<p>'+weather.alt.temp+'&deg;F</p></ul>';

      //chage skycons
      var skycons = new Skycons({"color": "gray"});
      skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
      skycons.play();


      $("#weather").html(html);
    },
    error: function(error) {
      $("#weather").html('<p>'+error+'</p>');
    }

  });
});

//date1
$(document).ready(function() {
  $.simpleWeather({
    location: 'Taipei, TW',
    woeid: '2306179',
    unit: 'c',
    success: function(weather) {
      html = '<p>'+weather.forecast[1].date+'<p>';
      html += '<p>'+weather.forecast[1].text+'</p>';
      html += '<p>'+weather.forecast[1].low+'&#126;'+weather.forecast[1].high+'&deg;'+weather.units.temp+'</p>';
  

      $("#date1").html(html);
    },
    error: function(error) {
      $("#date1").html('<p>'+error+'</p>');
    }
  });
});

//date2
$(document).ready(function() {
  $.simpleWeather({
    location: 'Taipei, TW',
    woeid: '2306179',
    unit: 'c',
    success: function(weather) {
      html = '<p>'+weather.forecast[2].date+'<p>';
      html += '<p>'+weather.forecast[2].text+'</p>';
      html += '<p>'+weather.forecast[2].low+'&#126;'+weather.forecast[2].high+'&deg;'+weather.units.temp+'</p>';


      $("#date2").html(html);
    },
    error: function(error) {
      $("#date2").html('<p>'+error+'</p>');
    }
  });
});

//date3
$(document).ready(function() {
  $.simpleWeather({
    location: 'Taipei, TW',
    woeid: '2306179',
    unit: 'c',
    success: function(weather) {
      html = '<p>'+weather.forecast[3].date+'<p>';
      html += '<p>'+weather.forecast[3].text+'</p>';
      html += '<p>'+weather.forecast[3].low+'&#126;'+weather.forecast[3].high+'&deg;'+weather.units.temp+'</p>';


  
      $("#date3").html(html);
    },
    error: function(error) {
      $("#date3").html('<p>'+error+'</p>');
    }
  });
});
